# -*- coding: utf-8 -*-
"""
Small synthetic-data unit tests for pmhp.data / pmhp.posterior /pmhp.likelihood.

Notes: tests are fully generated by Claude (model Sonnet 5).
Revision: Persia Luca (2026), Università della Svizzera italiana, Lugano, Switzerland
"""

import numpy as np
import pandas as pd
import pytest

from pmhp import data as pmhp_data
from pmhp import posterior as pmhp_posterior
from pmhp import likelihood as pmhp_likelihood


def test_calendar_tau_leap_year_folding():
    dates = pd.Series(pd.to_datetime(["2020-01-01", "2020-03-01", "2020-12-31", "2021-03-01"]))
    tau = pmhp_data.calendar_tau(dates)
    assert tau[0] == pytest.approx(0.0)
    # 2020 is a leap year: Feb 29 is folded onto Feb 28's position, so
    # Mar 1 2020 lands on the same seasonal day as Mar 1 in a non-leap year.
    assert tau[1] == pytest.approx(59.0)
    assert tau[3] == pytest.approx(59.0)
    assert tau[2] == pytest.approx(364.0)


def test_seasonal_features_unit_circle():
    tau = np.array([0.0, 91.25, 182.5, 273.75])
    cos, sin = pmhp_data.seasonal_features(tau)
    assert np.allclose(cos**2 + sin**2, 1.0)


def test_day_of_year_exposure_sums_to_window_length():
    start = pd.Timestamp("2020-01-01")
    end = pd.Timestamp("2021-01-01")  # 2020 is a leap year: 366 days
    T = float((end - start).total_seconds() / (24 * 3600))
    exposure = pmhp_data.day_of_year_exposure(start, end, T)
    assert exposure.sum() == pytest.approx(T)
    assert exposure.shape == (pmhp_data.SEASONAL_DAYS,)


def test_day_of_year_exposure_rejects_bad_window():
    start = pd.Timestamp("2020-01-01")
    with pytest.raises(ValueError):
        pmhp_data.day_of_year_exposure(start, start, 0.0)


def test_branching_prefix_detection():
    assert pmhp_posterior.branching_prefix(["alpha.1.1", "beta.1.1"]) == "alpha"
    assert (
        pmhp_posterior.branching_prefix(["branching_ratio.1.1", "beta.1.1"])
        == "branching_ratio"
    )
    with pytest.raises(KeyError):
        pmhp_posterior.branching_prefix(["mu.1", "beta.1.1"])


def test_log_mean_exp_matches_naive_for_small_values():
    x = np.array([-1.0, 0.0, 1.0])
    naive = np.log(np.mean(np.exp(x)))
    assert pmhp_likelihood.log_mean_exp(x) == pytest.approx(naive)
